import math

def generate_bottle_obj(filename, segments=32):
    # Define the profile curve (radius at different heights)
    # Height goes from 0 (bottom) to 1 (top)
    profile = [
        (0.0, 0.4),   # Bottom
        (0.1, 0.45),  # Base bulge
        (0.5, 0.45),  # Main body
        (0.7, 0.4),   # Shoulder start
        (0.8, 0.15),  # Neck start
        (0.95, 0.15), # Neck end
        (1.0, 0.18),  # Lip
    ]

    vertices = []
    uvs = []
    faces = []

    # Generate vertices and UVs
    for i, (h, r) in enumerate(profile):
        v = h  # v coordinate (0 to 1)
        for j in range(segments + 1):
            theta = (j / segments) * 2.0 * math.pi
            u = j / segments  # u coordinate (0 to 1)
            
            x = r * math.cos(theta)
            z = r * math.sin(theta)
            y = h * 3.0  # Scale height by 3
            
            vertices.append((x, y, z))
            uvs.append((u, v))

    # Generate faces (quads converted to two triangles)
    # The grid is len(profile) rows by (segments + 1) cols
    cols = segments + 1
    for i in range(len(profile) - 1):
        for j in range(segments):
            # Indices for the 4 corners of a quad
            v1 = i * cols + j + 1
            v2 = i * cols + (j + 1) + 1
            v3 = (i + 1) * cols + (j + 1) + 1
            v4 = (i + 1) * cols + j + 1

            # Triangle 1
            faces.append((v1, v2, v3))
            # Triangle 2
            faces.append((v1, v3, v4))

    # Write to OBJ file
    with open(filename, 'w') as f:
        f.write("# Bottle OBJ generated by Python\n")
        
        for v in vertices:
            f.write(f"v {v[0]:.4f} {v[1]:.4f} {v[2]:.4f}\n")
            
        for uv in uvs:
            f.write(f"vt {uv[0]:.4f} {uv[1]:.4f}\n")
            
        for face in faces:
            # OBJ indices are 1-based. Format: v/vt
            f.write(f"f {face[0]}/{face[0]} {face[1]}/{face[1]} {face[2]}/{face[2]}\n")

if __name__ == "__main__":
    generate_bottle_obj("assets/bottle.obj")
    print("Generated assets/bottle.obj successfully.")
